### ISSUE TITLE
bin/status.py: api exception

### ISSUE THREAD

**Issue by whilei** [ethereumproject/ecip1017test#3]
```
~/dev/etc/ecip1017test dev *% ⟠ ./bin/status.py
Nodes status
ID			PEERS	HEIGHT	HASH
2017-09-26 09:43:09,944 ERROR Certificate did not match expected hostname: 35.188.72.192. Certificate: {'subjectAltName': (('DNS', 'kubernetes'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default.svc.cluster.local'), ('IP Address', '35.188.72.192'), ('IP Address', '10.19.240.1')), 'notBefore': u'Sep 26 13:55:57 2017 GMT', 'serialNumber': u'17E31F9E974EF7A9471D672918D3519A', 'notAfter': 'Sep 25 13:55:57 2022 GMT', 'version': 3L, 'subject': ((('commonName', u'35.188.72.192'),),), 'issuer': ((('commonName', u'd2096ae7-3eff-489d-a33a-b1fb7573117e'),),)}
Traceback (most recent call last):
  File "./bin/status.py", line 70, in <module>
    list()
  File "./bin/status.py", line 62, in list
    pods = api.get_nodes()
  File "/Users/ia/dev/etc/ecip1017test/bin/rpc_api.py", line 74, in get_nodes
    ret = api.list_namespaced_pod("default", watch=False)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13060, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13162, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 226, in request
    raise ApiException(status=0, reason=msg)
kubernetes.client.rest.ApiException: (0)
Reason: SSLError
hostname '35.188.72.192' doesn't match either of 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local'

~/dev/etc/ecip1017test dev *% ⟠ ipconfig getifaddr en1
192.168.0.193
```

**Comment by splix** [comment]
It seems that you're using non-gcp cluster?

**Comment by whilei** [comment]
I think I am using GCP --
![screen shot 2017-09-26 at 10 07 18](https://user-images.githubusercontent.com/10228550/30867800-84af9c1a-a2a2-11e7-94f2-9ee5d0c065f8.png)

**Comment by splix** [comment]
did `deploy.sh` work for you?

**Comment by whilei** [comment]
it appears so -- 

```
~/dev/etc/ecip1017test dev *% ⟠ ./bin/deploy.sh etc-tester us-central1-a ecip1017test
Updated property [core/project].
Updated property [compute/zone].
Updated property [container/cluster].
Fetching cluster endpoint and auth data.
kubeconfig entry generated for ecip1017test.
service "gm1" created
service "gm2" created
service "g1" created
service "g2" created
service "g3" created
service "p1" created
service "p2" created
service "p3" created
replicationcontroller "node-gm1-rc" created
replicationcontroller "node-gm2-rc" created
replicationcontroller "node-g1-rc" created
replicationcontroller "node-g2-rc" created
replicationcontroller "node-g3-rc" created
replicationcontroller "node-p1-rc" created
replicationcontroller "node-p2-rc" created
replicationcontroller "node-p3-rc" created
Please give 2-3 minutes to spin up nodes before calling bin/status.py
~/dev/etc/ecip1017test dev *% ⟠ ./bin/status.py
Nodes status
ID			PEERS	HEIGHT	HASH
2017-09-26 09:36:00,378 ERROR Certificate did not match expected hostname: 35.188.72.192. Certificate: {'subjectAltName': (('DNS', 'kubernetes'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default.svc.cluster.local'), ('IP Address', '35.188.72.192'), ('IP Address', '10.19.240.1')), 'notBefore': u'Sep 26 13:55:57 2017 GMT', 'serialNumber': u'17E31F9E974EF7A9471D672918D3519A', 'notAfter': 'Sep 25 13:55:57 2022 GMT', 'version': 3L, 'subject': ((('commonName', u'35.188.72.192'),),), 'issuer': ((('commonName', u'd2096ae7-3eff-489d-a33a-b1fb7573117e'),),)}
Traceback (most recent call last):
  File "./bin/status.py", line 70, in <module>
    list()
  File "./bin/status.py", line 62, in list
    pods = api.get_nodes()
  File "/Users/ia/dev/etc/ecip1017test/bin/rpc_api.py", line 74, in get_nodes
    ret = api.list_namespaced_pod("default", watch=False)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13060, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13162, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 226, in request
    raise ApiException(status=0, reason=msg)
kubernetes.client.rest.ApiException: (0)
Reason: SSLError
hostname '35.188.72.192' doesn't match either of 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local'

```

**Comment by splix** [comment]
There're some discussions with same issue: https://github.com/kubernetes-incubator/client-python/issues/36 and https://github.com/kelproject/pykube/issues/29

Maybe you need to upgrade python libs

**Comment by whilei** [comment]
Yep, that did it! Thanks.
